### ISSUE TITLE
Firefox Add-on doesn't work when blocking "All third-party cookies"

### ISSUE THREAD

**Issue by BafDyce** [jeroenheijmans/advent-of-code-charts#26] opened 2018-12-10 17:37 UTC
I am using version **2.3.1** in **Firefox 63.0.3** (Arch Linux)

In the browser console, I see the following log messages:

```
Loading via readyState = interactive app.js:835:9
Going to construct App app.js:830:9
Constructing App app.js:316:13
Getting cache aoc-data-v1-/2018/leaderboard/private/view/<id> app.js:197:9
Found cache null app.js:287:17
Loading data from url https://adventofcode.com/2018/leaderboard/private/view/<id>.json app.js:301:17 
```

"Not working" means: I do not see any charts anywhere on the page. I looked at these places:

- In my private leaderboard overview
- On each private leaderboard page

I also already restarted firefox after installing the aoc-charts extension.

Other plugins that are installed:

- ublock origin
- noscript
- privacy badger
- https everywhere

Any help is welcome, if you want me to submit more debugging logs, just tell me what you need :-)

**Comment by jeroenheijmans** [comment] 2018-12-10 19:20
Sorry to hear it's not working. I'll do my best to try and find the root cause, but don't have immediate access to an Arch Linux install to test this.

Thank you for already a quite extended bug report, that really helps! The log you're showing seems mostly correct, except that I get an "Updating cache" message after your last "Loading data..." line.

That leads me to suspect that my script is not allowed to access `localStorage` and crashes before it can render anything. I've [spotted a "`permissions`" section in the manifest spec](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#API_permissions) which suggests my addon should ask for it explicitly, but then again my addon is working for me on Firefox.

The less likely alternative that occurs to me is that it is that Chart.js relies on some proprietary thing around canvas or rendering that is not included in your Firefox build (much like codecs might not be installed by default), but clutching at straws here.

Some things you could try @BafDyce if you find a moment:

- Temporarily disable the other addons, just to try if any one of them interferes with my plugin;
- If you have the time and tools, you could clone my repository, run the `build.sh`, go to `about:debugging` in Firefox, and "Load Temporary Addon" pointing at the build folder - possibly disabling the few lines of localStorage code for a moment.
- Try the (also cool!) [AoC Ranking Extension](https://addons.mozilla.org/en-US/firefox/addon/aoc-ranking/) for a moment: my localStorage code is loosely based on that addon's code (so whether that one does or doesn't work helps me a lot)

Again, thank you for a good bug report. Hope we can find the culprit. If I find time I might set up an Arch install to test, but won't have time for a few days at least to try this.

**Comment by BafDyce** [comment] 2018-12-10 21:10
@jeroenheijmans Thanks for the quick reply :)

It doesn't seem like its caused by the other addons. I can try building the addon myself in the next few days (do I need a firefox nightly installation for that or will it also work in stable firefox?). Also, where can I find the source code for the AoC ranking extension? Couldn't find it on the Addon-store page.

**Comment by BafDyce** [comment] 2018-12-14 08:43
Update: I just tested this addon on another machine (Linux Ubuntu, also Firefox).

I also played around with Firefox' settings and I found the following config setting which causes the error:

Firefox Settings -> Security & Privacy -> Content blocking -> Third party cookies -> tick "All third party cookies". If I change this setting to "Trackers" then the charts can be created/displayed. If I, afterwards, revert the setting to "All 3rd party cookies", existing charts are still displayed (until I restart Firefox), however no new charts are rendered (e.g. in a different leaderboard).

So this is NOT Arch/Linux-specific but is caused by Firefox' privacy settings (the default values on a new install work; if you change it to a more privacy protective setting, the AddOn stops working).

In the browser console, after the log outputs from the AddOn, I also see the following warning:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fonts.gstatic.com/s/sourcecodepro/v8/HI_XiYsKILxRpg3hIP6sJ7fM7PqtlsnDs-cq.woff2. (Reason: CORS request did not succeed).

Do you load fonts/assets from CDNs, such as gstatic? Would it be possible to add them as an asset to the AddOn itself (if the permission permits it). Alternatively, would it be possible to add a switch that makes the AddOn NOT load assets from third party sites? I don't really want to weaken my browser's privacy settings just for this AddOn :/

**Comment by jeroenheijmans** [comment] 2018-12-14 09:49
Thanks for **the repro, setting "Block cookies" to "All third-pary cookies"**, which has the same breaking effect on my Windows machine.

The option does say "(may cause websites to break)", which already hints at the problem that happened. But you're right when you say:

> I don't really want to weaken my browser's privacy settings just for this AddOn

I don't want you to have to do that either. So if I can find a fix I'll certainly implement it.

The font warning _might_ be a red herring though, I don't include any extra fonts in my plugin, I think "Source Code Pro" is loaded with this line in the AoC website itself:

```html
<link href='//fonts.googleapis.com/css?family=Source+Code+Pro:300&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
```

So the cookies blocking setting might cause the breakage in a different way, I suppose.

**Comment by BafDyce** [comment] 2018-12-14 12:39
Thanks for the quick reply. Yes, I know that it might break websites, but I can live with that. I find it funny, that it breaks addons too. To be fair, this setting is relatively new (only <1-2 months old) and Mozilla is still improving it. So maybe it's already a well-known problem? If I find some time, I can also try to research this.

> I don't want you to have to do that either. So if I can find a fix I'll certainly implement it.

Happy to hear :-) Always a good sign, if devs respect their users' privacy :)

You are right with the fonts thingy, really looks like a "false positive" in that case.

**Comment by BafDyce** [comment] 2018-12-14 12:51
So, I quickly looked at the issue with Burp [1]

Apparently, if your addon sends a request while Firefox is told to block "**All third-pary cookies**", then **no cookies** are sent in the request (even though it is for the same origin??). Either this is a bug in Firefox or an intended way? (Maybe you need to add some permission or set a specific parameter for the request?)

Due to the missing cookies, adventofcode.com redirects to the global leaderboard (not even it's json file) because it thinks the request comes from a not logged in user.

Hope this helps you on your further research.


[1] https://portswigger.net/burp/

**Comment by jeroenheijmans** [comment] 2018-12-23 22:39
I've spend 30 mins debugging this issue, but haven't found any solution, if there even is one. For future reference, what I've done:

- Load the add on without the security setting (so that the localStorage cache fills) and then enable the more secure cookie settings. Result: the addon gets stuff from localStorage and renders things nicely. If you clear local storage, the add on will break next load.
- Tried playing with the `permissions` part of the manifest (requesting "cookies" as well as host access): no success.
- Googling for various combinations of terms.
- Check if the `credentials: "same-origin"` options I pass to `fetch` could be tweaked (but "omit" won't help as then AoC won't give data, and the other one's even more aggressive).

I can't seem to find any solution to this. Perhaps this is _meant_ to be like this, as my Add On is in fact from a domain other than the AoC website, and shouldn't be able to use the cookies for that domain?

At this point I'll give up for the moment, leaving the issue open should anyone have a solution for us later on.

😢 🏳️

**Comment by BafDyce** [comment] 2019-01-06 11:10
@jeroenheijmans Thanks for looking into it. Maybe its also a bug in Firefox' blocking feature?

Also, I wonder whether the following (quite dirty) approach would be possible?
- test if the request to the json file returns meaningful data
- if not, inject a small javascript into the website which loads the data (since the javascript then resides on adventofcode.com, this *should* work) and stores it in some html element
- afterwards, the plugin reads this data and performs its usual task

Maybe I find some time in the next days to try this.

**Comment by jeroenheijmans** [comment] 2019-01-06 16:15
Yeah, could be that they still need to smooth out that new feature, and that it's a bug.

Personally, I don't intend to do too much on this plugin until next November, when AoC 2019 is hopefully nearing.

FWIW: I don't mind including a small hack like the one you describe as a workaround for the issue, not in the least because my plugin isn't (meant to be) a marvel of engineering anyways 😄. So if you find that it works, I'm happy to consider including a fix in next year's batch of releases!

**Comment by jeroenheijmans** [comment] 2020-12-09 00:23
For anyone landing here, I don't think there's much to be done on the extension side of things. In the end, my extension _is_ only able to function as a third-party bit of code accessing the advent of code data. I don't think (but am gladly proven wrong!) there's any `manifest.json` feature to help me "be" a first party - and this is good! No one else besides the TLD owner should be able to impersonate the main domain.

If you're using any kind of cookie blocking (and as a user I hope this becomes more and more standard!), you'll need an exception to allow the extension to function. Short of that, we'd need the AoC site or "API" to change, and that's not likely to happen soon.

Gonna close this issue, it'll remain findable for those in need.

----

Adding some tips from a [kind reddit user](https://www.reddit.com/r/adventofcode/comments/k7usko/browser_extension_with_private_leaderboard_graphs/gf1rxpt), should it help someone:

> I use uMatrix to block all kinds of internet stank. My rules for adventofcode are:
> 
>  ```
> adventofcode.com 1st-party cookie allow
> adventofcode.com 1st-party other allow
> adventofcode.com 1st-party script allow
> 
> With those in place, your extension doesn't work for me.
> 
> After some checking the uMatrix logger tweaking and I added this rule to get it working.
> 
> ```
> behind-the-scene adventofcode.com xhr allow
> behind-the-scene adventofcode.com cookie allow
> ```

**Closed** 2020-12-09 00:24 UTC
Labels: bug
